<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	<AssemblyName>JobBank</AssemblyName>
  </PropertyGroup>

	<PropertyGroup>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
		<GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="JobBank.Data\**" />
	  <Compile Remove="JobBank.EtlConsole\**" />
	  <Compile Remove="JobBank.Management.DTO\**" />
	  <Compile Remove="JobBank.Management\**" />
	  <Compile Remove="JobBank.ModelDTO\**" />
	  <Compile Remove="Logs\**" />
	  <Compile Remove="WORKSCommons.Tests\**" />
	  <Content Remove="JobBank.Data\**" />
	  <Content Remove="JobBank.EtlConsole\**" />
	  <Content Remove="JobBank.Management.DTO\**" />
	  <Content Remove="JobBank.Management\**" />
	  <Content Remove="JobBank.ModelDTO\**" />
	  <Content Remove="Logs\**" />
	  <Content Remove="WORKSCommons.Tests\**" />
	  <EmbeddedResource Remove="JobBank.Data\**" />
	  <EmbeddedResource Remove="JobBank.EtlConsole\**" />
	  <EmbeddedResource Remove="JobBank.Management.DTO\**" />
	  <EmbeddedResource Remove="JobBank.Management\**" />
	  <EmbeddedResource Remove="JobBank.ModelDTO\**" />
	  <EmbeddedResource Remove="Logs\**" />
	  <EmbeddedResource Remove="WORKSCommons.Tests\**" />
	  <None Remove="JobBank.Data\**" />
	  <None Remove="JobBank.EtlConsole\**" />
	  <None Remove="JobBank.Management.DTO\**" />
	  <None Remove="JobBank.Management\**" />
	  <None Remove="JobBank.ModelDTO\**" />
	  <None Remove="Logs\**" />
	  <None Remove="WORKSCommons.Tests\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="msbuild.binlog" />
	</ItemGroup>

	<!--ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup-->

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
		<PackageReference Include="Blazor.Extensions.Storage" Version="1.0.0" />
		<PackageReference Include="ChartJs.Blazor" Version="1.1.0" />
		<PackageReference Include="ChartJs.Blazor.Fork" Version="2.0.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.Agents.AI" Version="1.0.0-rc4" />
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-rc4" />

		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="10.0.2" />

		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.3" />

		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />

		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.0.0" />

		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />

		<PackageReference Include="Microsoft.SemanticKernel.Plugins.OpenApi" Version="1.77.0" />

		<PackageReference Include="Newtonsoft.Json.Schema" Version="4.0.1" />
		<PackageReference Include="OpenAI" Version="2.8.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
    <Content Update="wwwroot\app.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
	  <Folder Include="Components\Account\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include=".github\workflows\build.yml" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="JobBank.Data\JobBank.Data.csproj" />
	  <ProjectReference Include="JobBank.Management.DTO\JobBank.Management.DTO.csproj" />
	</ItemGroup>

</Project>
