<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>JobBank.Management</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\JobBank.ModelDTO\JobBank.ModelDTO.csproj" />
	</ItemGroup>
</Project>
